Telephone Number Validator
faridafaqiri/telephone-number-validator pull request #1
Opened 2024-07-03 14:17 UTC by faridafaqiri

## Pull Request Description
Description:
This pull request enhances the functionality and user experience of the Telephone Number Validator web application. It introduces input validation for various US phone number formats and improves the visual presentation using CSS. Additionally, it adds clear functionality to reset input fields and results.

Changes Made:
Implemented JavaScript validation for US phone numbers.
Styled the application with a phone-themed design using CSS.
Added functionality to clear input fields and results.
Updated README.md with detailed project information, setup instructions, and usage guidelines.

2024-07-04 18:51 UTC, faridafaqiri commented
@Fikrat2002
hi dear!
I'm waiting for your feedback.

2024-07-05 06:15 UTC, Fikrat2002 commented
> @Fikrat2002 hi dear! I'm waiting for your feedback.

Hi @far_faqiri 🙋‍♀,

Great job! 💯 You've nailed all the project requirements👏Your feature is complete! Congratulations!!! 🎊🏆

Status: Approved ✅
Everything looks perfect, merge your project 🏆🎊👏

Highlights 💡
🏆 Successfully implemented a great design
✅ Created a professional repository with your project name
✅ Passed FreeCodeCamp requirements for the project 
✅ Used Gitflow correctly by creating a development branch, setting it as default, and making commits on your feature branch
✅ Wrote meaningful commit messages
✅ Set up appropriate linter configurations based on your project's language
✅ No linter errors!
✅ Followed the task and used command-line commits
✅ Submitted a pull request from your feature branch to the development branch and shared the link for review
✅ Provided a clear and detailed description of your work in the PR
✅ Maintained clean code
✅ Created a professional README.md file in your repository
✅ The project is responsive

2024-07-05 06:35 UTC, faridafaqiri commented
@ahzamir
Hi dear mentor 
please review my project.

2024-07-05 13:05 UTC, ahzamir requested changes
### Hi @faridafaqiri 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- Well done you have finished lots of requirements but still your code misses some part of the requirements and you need to work on it please check the comments below for more details:

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image](https://github.com/faridafaqiri/telephone-number-validator/assets/96838030/311267e4-4230-4624-8f43-87f64e9b922a)

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)
b64e13140efa)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Telephone Number Validator project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
❌Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
❌Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

2024-07-05 13:05 UTC, ahzamir commented on script.js
> +});
- [OPTIONAL] - Try to add your Event Listeners in while DOM content is loading, it helps to add all of your event listeners to be ready to the action right when your page loads and prevents any side effects below is an example to help you do that:

```javascript
document.addEventListener('DOMContentLoaded', () => {
  //In here add all of your addEventListener functions
  // don't forget to add the constants that you need in your event listeners here as the scope of this one is higher than other codes
  // As an Example I added only one Event Listener example here, you add your own:
  
  const clearBtn = document.getElementById('clear-btn');
  const resultsDiv = document.getElementById('results-div');
  
  clearBtn.addEventListener('click', () => {
    resultsDiv.innerHTML = '';
  });
})
```

2024-07-05 13:07 UTC, ahzamir requested changes

2024-07-05 13:07 UTC, ahzamir commented on styles.css
- Although your design is looking very great but still your design is not responsive:
![image](https://github.com/faridafaqiri/telephone-number-validator/assets/96838030/43cf3b6b-c61b-43a0-a4fe-02516eaba4b3)

2024-07-05 13:12 UTC, Fikrat2002 commented
> 
> 
> 
> 
> ### Hi @faridafaqiri 🙋‍♀️,
> 
> 
> 
> > Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊
> 
> 
> 
> - Well done you have finished lots of requirements but still your code misses some part of the requirements and you need to work on it please check the comments below for more details:
> 
> 
> 
> - **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.
> 
> 
> 
> - Share your Project on your LinkedIn account and add a proud moment text with a screenshot.
> 
> 
> 
> - Well Done great design Implemented. 🎯🎉👍
> 
> ![image](https://github.com/faridafaqiri/telephone-number-validator/assets/96838030/311267e4-4230-4624-8f43-87f64e9b922a)
> 
> 
> 
> # Status: Required Changes 🔁
> 
> Make changes to your code and commit and request for a re-review.
> 
> 
> 
> ![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)
> 
> b64e13140efa)
> 
> 
> 
>  ## Highlights 🌞
> 
> 
> 
> 🎉 Great Design Implemented 
> 
> ✔️ Created a professional Repo (You created a repository with your project name)
> 
> ✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
> 
> ✔️ Commit messages are meaningful
> 
> ✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
> 
> ✔️ No linter errors (All linters checks have been passed 🟢)
> 
> ✔️ You have followed the Telephone Number Validator project task and committed using the command line
> 
> ✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
> 
> ✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
> 
> ❌Your code is clean
> 
> ✔️Your repo has a professional README.md file
> 
> ✔️ Your partner has reviewed your repo
> 
> ❌Your design is responsive
> 
> 
> 
> **Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**
> 
> 
> 
> 

Hello dear mentor, I just want to mention that I don't understand what the problem exactly is but when I checked Farida's project her design was responsive

2024-07-05 14:30 UTC, ahzamir commented
@Fikrat2002 

- You have to check for responsiveness in the inspect:
  - See what result I get from inspect the mobile version:
  
![image](https://github.com/faridafaqiri/telephone-number-validator/assets/96838030/f9baeded-cb1a-4378-9cf8-b77f934f1b61)

2024-07-05 14:31 UTC, ahzamir commented
- The bottom of the page does not have background

2024-07-05 15:32 UTC, faridafaqiri commented
@ahzamir 
which part of the code is not clean?
I checked but all of my is clean.

2024-07-05 17:33 UTC, faridafaqiri commented
@Fikrat2002  
please give me feedback again .

2024-07-05 17:45 UTC, faridafaqiri commented
@ahzamir 
I responsive my project and clean the code also made changes in JavaScript code.

2024-07-05 18:11 UTC, Fikrat2002 commented
> @Fikrat2002 
> 
> 
> 
> - You have to check for responsiveness in the inspect:
> 
>   - See what result I get from inspect the mobile version:
> 
>   
> 
> ![image](https://github.com/faridafaqiri/telephone-number-validator/assets/96838030/f9baeded-cb1a-4378-9cf8-b77f934f1b61)
> 
> 

You were right🥲

2024-07-05 18:12 UTC, Fikrat2002 commented
> > @Fikrat2002 
> > 
> > 
> > 
> > - You have to check for responsiveness in the inspect:
> > 
> >   - See what result I get from inspect the mobile version:
> > 
> >   
> > 
> > ![image](https://github.com/faridafaqiri/telephone-number-validator/assets/96838030/f9baeded-cb1a-4378-9cf8-b77f934f1b61)
> > 
> > 
> 
> You were right🥲

@faridafaqiri 
You have applied the feedbacks and I see no further issues

2024-07-08 03:59 UTC, faridafaqiri commented
@ahzamir hi 
teacher please give me feedback.

2024-07-08 16:24 UTC, ahzamir approved these changes
### Hi @faridafaqiri 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image](https://github.com/faridafaqiri/telephone-number-validator/assets/96838030/08fc9e11-bdba-425b-af26-0e4be7d10194)

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![WinkThumbsUpGIF](https://github.com/ZohalMirkhel/palindrome/assets/96838030/e5ee293e-072a-4806-bde0-b64e13140efa)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Telephone Number Validator project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

2024-07-09 18:11 UTC, merged